<?php

namespace AppBundle\Repository;

/**
 * PlatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatesRepository extends \Doctrine\ORM\EntityRepository
{
}
